tools:
  external_code_coverage:
    timeout: 1800
    runs: 3

build:
  environment:
    php:
      version: 7.2

  nodes:
    analysis:
      environment:
        php:
          ini:
            'memory_limit': -1
          pecl_extensions:
            - redis
            - memcached
            - apcu
      dependencies:
        override:
          - composer require --dev phpstan/phpstan-shim:^0.11 psalm/phar:^3.0
      tests:
        override:
          - phpcs-run src/ tests/
          - command: vendor/bin/phpstan.phar analyse --error-format checkstyle src/ > checkstyle.xml
            analysis:
              file: checkstyle.xml
              format: 'general-checkstyle'
          - command: vendor/bin/psalm.phar --show-info=false --report=checkstyle.xml
            analysis:
              file: checkstyle.xml
              format: 'general-checkstyle'

build_failure_conditions:
  - 'issues.count > 0'
  - 'project.metric_change("scrutinizer.test_coverage", < -0.01)'
